FROM golang:1.12

RUN apt-get update && apt-get install -y --no-install-recommends \
        gettext-base \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /apnaschool/src/github.com/ahab94/apnaschool

COPY scripts/. /opt/

RUN curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.19.1

RUN apt install gcc

ENV GO111MODULE=on

RUN go mod download

RUN CGO_ENABLED=0

ARG DEVELOPER
