FROM golang:1.13

RUN apt-get update && apt-get install -y --no-install-recommends \
        gettext-base \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /apnaschool/src/github.com/ahab94/apnaschool

ENV GO111MODULE=on

RUN go get github.com/golangci/golangci-lint/cmd/golangci-lint \
    && go get golang.org/x/tools/cmd/goimports

RUN CGO_ENABLED=0

ARG DEVELOPER
