FROM golang:1.12

RUN apt-get update && apt-get install -y --no-install-recommends \
        gettext-base \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/. /opt/

RUN curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.19.1

RUN apt install gcc && apt install build-essentials

ENV GO111MODULE=on

RUN go mod download

RUN CGO_ENABLED=0

ARG DEVELOPER
